---
driver:
  name: vagrant
  customize:
    memory: 512

provisioner:
  name: chef_zero

platforms:
  # To run test-kitchen for OS X, create a box for 10.9, and add it to vagrant. See for example,
  # https://github.com/timsutton/osx-vm-templates
  # https://github.com/opscode/bento/blob/master/packer/macosx-10.9.json
  - name: macosx-10.9

suites:
  - name: default
    run_list:
      - recipe[pantry::default]
    attributes:
