---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_zero
  data_path: test/shared
  chef_omnibus_install_options: -P chefdk
  chef_omnibus_root: /opt/chefdk

platforms:
  # To run test-kitchen for OS X, create a box for 10.9 and 10.10, and
  # add it to vagrant. See for example,
  # https://github.com/timsutton/osx-vm-templates
  # https://github.com/opscode/bento/blob/master/packer/macosx-10.9.json
  - name: macosx-10.9
    driver:
      box: chef/macosx-10.9
  - name: macosx-10.10
    driver:
      box: chef/macosx-10.10
  - name: centos-7.2
  - name: debian-8.4

suites:
  # this makes for silly names, but this will be different across platforms
  - name: osx
    run_list:
      - recipe[pantry]
    attributes:
      homebrew:
        formulas:
          - redis
        casks:
          - caffeine
    excludes: ["centos-7.1", "debian-8.1"]

  - name: debian
    run_list:
      - recipe[pantry]
    attributes:
    excludes: ["macosx-10.9", "macosx-10.10", "centos-7.1"]

  - name: rhel
    run_list:
      - recipe[pantry]
    attributes:
    excludes: ["macosx-10.9", "macosx-10.10", "debian-8.1"]
