name              'pantry'
maintainer        'Joshua Timberman'
maintainer_email  'joshua@getchef.com'
license           'Apache 2.0'
description       'Chef Pantry is a workstation automation cookbook'
version           '0.1.1'
depends           'build-essential', '~> 2.1.3'
depends           'homebrew', '~> 1.9'
