name              'pantry'
maintainer        'Joshua Timberman'
maintainer_email  'joshua@getchef.com'
license           'Apache 2.0'
description       'Chef Pantry is a workstation automation cookbook'
version           '0.1.3'
depends           'homebrew', '~> 1.11'
depends           'chocolatey', '~> 0.2'
